name: Package
description: Docker build, tag and push plugin for buildkite
author: https://github.com/healthforge
requirements:
  - bash
  - git
configuration:
  properties:
    registries:
      type: array
      items:
        type: string
    src:
      type: string
    tags:
      type: array
      items:
        type: string
  required:
    - registries
    - src
