#!/usr/bin/env bash
set -euo pipefail

# Tag safe chars
BRANCH=${BUILDKITE_BRANCH//[^a-zA-Z0-9\.-]/_}
git fetch --tags
DESCRIBE=$(git describe --always)
for TAG in latest $BUILDKITE_BUILD_NUMBER $BUILDKITE_COMMIT $BRANCH $DESCRIBE; do
  docker tag ${BUILDKITE_PLUGIN_DOCKER_TAGS_REGISTRY}:${BUILDKITE_PLUGIN_DOCKER_TAGS_TAG} ${BUILDKITE_PLUGIN_DOCKER_TAGS_REGISTRY}:${TAG}
  docker push ${BUILDKITE_PLUGIN_DOCKER_TAGS_REGISTRY}:${TAG}
done
